* Etu's Slim Framework 4 Skeleton Application
This is an opinionated template for PHP projects using Slim Framework 4 that
has some care and thought put into error handling and logging.

It comes with the following custom bits:
 - Custom exceptions that supports something that works like PSR-3 context
   and specifying the log level for each exception type.
 - Custom error handler to handle these exceptions and log levels
 - Custom shutdown handler to log using the error handler

It's built on composer, Slim 4, PHP-DI, Monolog and Slim's PSR-7
implementation.

It also provides some response helpers to make it easier to write responses.

** Initial set up
Before running the code you should enter the =app/= directory and run
=composer install= to have all the required dependencies.

** Running the container
I've provided the nice shorthand =make run= to run docker-compose to start
up the environment. This will by default launch a container that listen on
the following address: http://127.0.0.1:8901/

** Running the tests
Yet again I have a shorthand for this called =make test= to run tests with
=phpunit=.
