FROM php:8.0-fpm

##
## Here you can customize your PHP container by doing things such as:
##

##
## Running an update to destroy the reproducibility of the image
##
# RUN apt-get update

##
## Install postgresql extensions
##
# RUN apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql
