---
name: Codestyle checks

'on':
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  phpcs:
    name: Run PHP Codesniffer style checks for PSR12
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prefetch shell.nix
        run: 'nix-shell --run true'

      - run: nix-shell --run "make phpcs"

  phpstan:
    name: Run phpstan style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prefetch shell.nix
        run: 'nix-shell --run true'

      - run: nix-shell --run "cd app && composer install"
      - run: nix-shell --run "make phpstan"

  yamllint:
    name: Run yamllint on github actions files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prefetch shell.nix
        run: 'nix-shell --run true'

      - run: nix-shell --run "make yamllint"
