---
name: Codestyle checks

'on':
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  phpcs:
    name: Run PHP Codesniffer style checks for PSR12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-shell --run "make phpcs"

  yamllint:
    name: Run yamllint on github actions files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-shell --run "make yamllint"
