---
name: Validate composer dependencies

'on':
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  validate-deps:
    name: Validate composer dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.6.0

      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prefetch shell.nix
        run: 'nix-shell --run true'

      - run: nix-shell --run "make composer-validate"

  security-advisories:
    name: Check deps against Roave Security Advisories
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.6.0

      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prefetch shell.nix
        run: 'nix-shell --run true'

      - run: nix-shell --run "make security-advisories"
